### ISSUE TITLE
Parsing error: Loader Url has no sync mode

### ISSUE THREAD

**Issue by tvvignesh** [dotansimha/graphql-eslint#132]
Hi. I was trying out this eslint plugin today and I am facing this error in all my GQL files both when linting via the CLI as well as the VSCode extension.

<img width="356" alt="1" src="https://user-images.githubusercontent.com/1165845/97776894-09e35280-1b92-11eb-8b6d-de2316012a67.png">

This error is thrown for every GQL file I use.

I tried to isolate the problem by removing all other eslint rules and just having this plugin around and still had this issue.

My `graphql-config` is configured correctly cause both the codegen and the VSCode GraphQL extension which uses it are working correctly. I am using multiple projects with both remote and local schema which works well with codegen and extension.

I also noticed other people reporting similar error but with apollo eslint rather:

https://github.com/apollographql/eslint-plugin-graphql/issues/287
https://github.com/apollographql/eslint-plugin-graphql/issues/270#issuecomment-700032602

Any clues? Thanks.

My `.eslintrc` file:

```
{
  "overrides": [
    {
      "files": ["*.gql"],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      "rules": {
        "avoid-operation-name-prefix": [
          "error",
          { "keywords": "get" }
        ],
        "input-name": [
          "error",
          { "checkInputType": true }
          ],
          "description-style": [
          "error",
          { "style": "block" }
          ],
          "naming-convention": [
          "error",
          {
            "FieldDefinition": "camelCase",
            "ObjectTypeDefinition": "PascalCase"
          }
          ],
          "no-anonymous-operations": ["error"],
          "require-deprecation-reason": "error",
          "no-case-insensitive-enum-values-duplicates": ["error"],
          "no-operation-name-suffix": ["error"],
          "require-id-when-available": ["error",
          {
            "fieldName": "id"
          }
          ],
          "validate-against-schema": ["error"],
          "require-description": [
            "error",
            { "on": ["ObjectTypeDefinition", "FieldDefinition"] }
          ]
      }
    }
  ]
}
```

My `package.json`

```json
"name":"...",
"version":"...",
"scripts": {
    "lint": "eslint --ext=.gql ./packages",
}
"devDependencies": {
    "@graphql-codegen/add": "^2.0.1",
    "@graphql-codegen/cli": "^1.17.10",
    "@graphql-codegen/typed-document-node": "^1.17.9",
    "@graphql-codegen/typescript": "^1.17.10",
    "@graphql-codegen/typescript-operations": "^1.17.8",
    "@graphql-codegen/typescript-resolvers": "^1.17.10",
    "@graphql-eslint/eslint-plugin": "^0.4.1",
    "@graphql-typed-document-node/core": "^3.1.0",
    "@types/body-parser": "^1.19.0",
    "@types/express": "^4.17.8",
    "@types/node": "^14.11.8",
    "@types/qs": "6.9.5",
    "@typescript-eslint/eslint-plugin": "^4.4.1",
    "@typescript-eslint/parser": "^4.4.1",
    "concurrently": "^5.3.0",
    "eslint": "^7.11.0",
    "globby": "^11.0.1",
    "morgan": "^1.10.0",
    "nodemon": "^2.0.5",
    "plop": "^2.7.4",
    "rimraf": "^3.0.2",
    "typedoc": "^0.19.2",
    "typescript": "4.0.3",
    "utility-types": "^3.10.0"
  },
  "dependencies": {
    "graphql": "^15.4.0",
    "graphql-modules": "^1.0.0-alpha.2"
  }
```

**CC:** @dotansimha

**Comment by dotansimha** [comment]
I see, thank you for reporting this @tvvignesh .
@kamilkisiela @ardatan what do you think? Do you think there is a way to allow sync loading from a url? [ESLint parser is limited to sync only](https://github.com/eslint/eslint/blob/82669fa66670a00988db5b1d10fe8f3bf30be84e/lib/linter/linter.js#L654-L656)

**Comment by kamilkisiela** [comment]
Doing http in sync will require to run it through `child_process` so it will be node-only. Not sure if it's an issue or might be in future.

**Comment by dotansimha** [comment]
I think it's node-only any way, no? we are using `fs` and other things there... just make sure to require it lazily..  
Or maybe you can check the environment before running it.

**Comment by kamilkisiela** [comment]
I think it's node-only but Ricky did some work to run it in browser and to make it work with GraphiQL. We can go with node-only.

**Comment by ardatan** [comment]
@kamilkisiela @dotansimha `sync-fetch` has both browser and node implementations.

**Comment by dotansimha** [comment]
Thank you @ardatan for the fix (https://github.com/ardatan/graphql-tools/pull/2192). 
@tvvignesh can you please try to add a Yarn resolution for that specific version of that loader? It should allow you to check the fix before we merge it. 

```json
  "resolutions": {
     "@graphql-tools/url-loader": "6.4.0-alpha-00cebee1.0"
  }
```

**Comment by tvvignesh** [comment]
@dotansimha Sure. Will check and report back in 10 minutes.

**Comment by tvvignesh** [comment]
@dotansimha @ardatan Perfect! This works great. Just tested it out. You can close this.

**Comment by dotansimha** [comment]
Awesome, thanks, let's keep it open until we'll have graphql-tools > graphql-config > graphql-eslint released :)

**Comment by dotansimha** [comment]
graphql-config @ 3.1.0 available now, please update and it should fix that issue :)
