### ISSUE TITLE
UPPER_CASE and snake_case naming conventions prevent numbers from being used

### ISSUE THREAD

**Issue by acidoxee** [dotansimha/graphql-eslint#175]
Because of the regexes used, numbers can't be used with `UPPER_CASE` and `snake_case` formats :

https://github.com/dotansimha/graphql-eslint/blob/ee9500dadffe0bd5e5957f0b852072a439132416/packages/plugin/src/rules/naming-convention.ts#L4-L9

For instance, `my_s3xy_string` would fail `snake_case` naming convention, as would `MY_S3XY_STRING` for the `UPPER_CASE` one. We don't use snake_case, but we have a bunch of uppercase enums with numbers in them, so spotting this problem was pretty obvious in our codebase.

Thanks a lot for the effort put into this library, looking forward to seeing it grow among the community 💪

**Comment by dotansimha** [comment]
Thank you @acidoxee ! 
@eddeee888 suggested a similar idea here: https://github.com/dotansimha/graphql-eslint/issues/195

**Comment by dotansimha** [comment]
Fixed in: https://github.com/dotansimha/graphql-eslint/pull/246

**Comment by dotansimha** [comment]
Fix available in `@graphql-eslint/eslint-plugin@0.7.0`
