### ISSUE TITLE
parseForESLint performance

### ISSUE THREAD

**Issue by henryqdineen** [dotansimha/graphql-eslint#181]
Running graphql-eslint on our projects is slower than expected. I did some profiling and noticed that `loadSchemaSync()` is responsible for several seconds on execution time. I added some naive memoization to that code (just based on `config.schema`) and the performance improved. 

Do you think this memoization is something we could support? Would it cause any issues? Should there be an option to enable the memoization?

I can make a PR if needed but I wanted to make sure it wouldn't break any assumption. If memoization can be based on `config.schema` it should be straightforward but I notice that the `config` is being spread into `loadSchemaSync()` options and changes every time. Is there any overlap between `ParserOptions` and `LoadSchemaOptions`? It wasn't obvious to me. 

https://github.com/dotansimha/graphql-eslint/blob/15176710527dd85621ebebde3cd0d0d30b7ca584/packages/plugin/src/parser.ts#L93-L94

Thanks!

**Comment by dotansimha** [comment]
thank you for reporting this @henryqdineen ! 
I started to do some optimizations here: https://github.com/dotansimha/graphql-eslint/pull/142 , hope to get some progress on this later this week :)

**Comment by dotansimha** [comment]
@henryqdineen can you please try `@graphql-eslint/eslint-plugin@0.5.0-alpha-c082a44.0`? It should cache the loaded schema and have better performance.

**Comment by henryqdineen** [comment]
Thanks @dotansimha! There is definitely a noticeable improvement there. I did have one question about the changes that I commented on inline (https://github.com/dotansimha/graphql-eslint/pull/142/files#r535305214)

**Comment by dotansimha** [comment]
Should be better with `@graphql-eslint/eslint-plugin@0.5.0`.
