### ISSUE TITLE
Issues when using validate-against-schema against multiple projects with graphql-config

### ISSUE THREAD

**Issue by tvvignesh** [dotansimha/graphql-eslint#222]
Hi. I have multiple projects configured using `graphql-config` each with its own set of schema and each set of documents pointing to a different schema.

Now, this works well with VSCode GraphQL properly giving me suggestions/autocomplete based on `graphql-config` from the appropriate schema.

But the `validate-against-schema` rule of `graphql-eslint` mixes it all up and validates the document against the wrong schema throwing errors.

**Errors thrown by GraphQL ESLint**

![image](https://user-images.githubusercontent.com/1165845/102375779-ead93c80-3fe8-11eb-827f-2bcd03f199a2.png)

**Proper Suggestions as provided by VSCode GraphQL**

![image](https://user-images.githubusercontent.com/1165845/102375890-0cd2bf00-3fe9-11eb-8eac-d4f5036d6b9d.png)

Using version: `"@graphql-eslint/eslint-plugin": "^0.5.0-alpha-ec33023.0",`

**CC:** @dotansimha

**Comment by dotansimha** [comment]
@tvvignesh I deprecated `validate-against-schema` and separated all validation to it's own rules. Will release very soon. It should allow easier integration with these validations.

**Comment by tvvignesh** [comment]
@dotansimha Sure. Actually, I think this might be a different issue. Just trying to wrap my head around this. Since I use stitching with type merging, multiple services contribute a portion of same types and when I supply the GQL URL of all these services to GQL Config, I guess GraphQL ESLint wouldn't be able to comprehend this. Will PM you on discord about this.

**Comment by tvvignesh** [comment]
@dotansimha As discussed in discord with you. This works for me now after doing static generation and encapsulating schema. You can close this when you feel comfortable. Thanks.
