### ISSUE TITLE
Can't lint graphql operation inside .js or .jsx files whith graphql-config

### ISSUE THREAD

**Issue by EmrysMyrddin** [dotansimha/graphql-eslint#232]
## Context

Today, `graphql-eslint` is loading schema and operations via `graphql-config` if available and not disable. Otherwise, it uses directly `graphql-tools` and `parserOptions` of eslint configuration file.

## Problem

When parsing schema and operations directly via `graphql-tools`, we use some loaders such as `CodeFileLoader` which allow to parse graphql inside JavaScript and TypeScript files.

But when we use `graphql-config`, this loaders are not used by default.

This lead to projects not lintable if used with graphql-config.

**Comment by dotansimha** [comment]
Fix available in `@graphql-eslint/eslint-plugin@0.7.0`!
