### ISSUE TITLE
getting error 'parserOptions.operations' in yarn workpsace

### ISSUE THREAD

**Issue by takumiya081** [dotansimha/graphql-eslint#260]
I like this package😍
I use yarn workspace and getting error 

```
ESLint: 7.17.0

Error: Rule 'require-id-when-available' requires 'parserOptions.operations' to be set and loaded. See http://bit.ly/graphql-eslint-operations for more info
Occurred while linting /home/miyata/dev/experiments/eslint-graphql-example/packages/packageB/src/sample.graphql:1
    at requireSiblingsOperations (/home/miyata/dev/experiments/eslint-graphql-example/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:24:15)
    at SelectionSet (/home/miyata/dev/experiments/eslint-graphql-example/node_modules/@graphql-eslint/eslint-plugin/index.cjs.js:876:34)
    at /home/miyata/dev/experiments/eslint-graphql-example/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/miyata/dev/experiments/eslint-graphql-example/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/miyata/dev/experiments/eslint-graphql-example/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/miyata/dev/experiments/eslint-graphql-example/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/home/miyata/dev/experiments/eslint-graphql-example/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/home/miyata/dev/experiments/eslint-graphql-example/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/miyata/dev/experiments/eslint-graphql-example/node_modules/eslint/lib/linter/linter.js:952:32
```

I created sample repo https://github.com/takumiya081/eslint-graphql-not-work-sample
eslintrc: https://github.com/takumiya081/eslint-graphql-not-work-sample/blob/main/packages/packageB/.eslintrc.js

**Comment by dotansimha** [comment]
@takumiya081 execution of ESLint and loading the files is done based on `cwd` while the script is executed.
If you are using this in a monorepo setup, you can either use `.js` extension for the eslint config file and then you can use `__dirname` to build the actual path, or you can put the entire eslint configuration in the root of your monorepo.

**Comment by takumiya081** [comment]
@dotansimha 
thank you for helping.

I fix `eslint.config.js` like that
```js
      parserOptions: {
        schema: path.resolve(__dirname, '../packageA/schema.graphql'),
        operations: [path.resolve(__dirname, './src/**/*.graphql')],
      },
```
but got same error.
I tried removing `.graphqlrc.yml` file, then it's work.

When exists graphql-config file in monorepo, 
https://github.com/dotansimha/graphql-eslint/blob/a2b71f6be17ff57614f57b3648ae2256cc834ea9/packages/plugin/src/sibling-operations.ts#L70

`projectForFile`  is
```
GraphQLProjectConfig {
  filepath: '/home/miyata/dev/experiments/eslint-graphql/.graphqlrc.yml',
  dirpath: '/home/miyata/dev/experiments/eslint-graphql',
  name: 'default',
  extensions: {},
  schema: 'packages/packageA/schema.graphql',
  include: undefined,
  exclude: undefined,
  isLegacy: true,
  _extensionsRegistry: GraphQLExtensionsRegistry {
    _extensions: { endpoints: [Object], 'graphql-eslint-loaders': [Object] },
    loaders: { schema: [LoadersRegistry], documents: [LoadersRegistry] }
  }
}
```

so `siblings` is empty array

**Comment by dotansimha** [comment]
> @dotansimha
> thank you for helping.
> 
> I fix `eslint.config.js` like that
> 
> ```js
>       parserOptions: {
>         schema: path.resolve(__dirname, '../packageA/schema.graphql'),
>         operations: [path.resolve(__dirname, './src/**/*.graphql')],
>       },
> ```
> 
> [takumiya081/eslint-graphql-not-work-sample](https://github.com/takumiya081/eslint-graphql-not-work-sample)
> but got same error.
> I tried removing `.graphqlrc.yml` file, then it's work.
> 
> When exists graphql-config file in monorepo,
> https://github.com/dotansimha/graphql-eslint/blob/a2b71f6be17ff57614f57b3648ae2256cc834ea9/packages/plugin/src/sibling-operations.ts#L70
> 
> `projectForFile` is
> 
> ```
> GraphQLProjectConfig {
>   filepath: '/home/miyata/dev/experiments/eslint-graphql/.graphqlrc.yml',
>   dirpath: '/home/miyata/dev/experiments/eslint-graphql',
>   name: 'default',
>   extensions: {},
>   schema: 'packages/packageA/schema.graphql',
>   include: undefined,
>   exclude: undefined,
>   isLegacy: true,
>   _extensionsRegistry: GraphQLExtensionsRegistry {
>     _extensions: { endpoints: [Object], 'graphql-eslint-loaders': [Object] },
>     loaders: { schema: [LoadersRegistry], documents: [LoadersRegistry] }
>   }
> }
> ```
> 
> so because `documents` property is undefined, `siblings` is empty array

I see, you can add `skipGraphQLConfig: true` to skip the loading of `.graphqlrc.yml` :) (see https://github.com/dotansimha/graphql-eslint/blob/master/docs/parser-options.md)

**Comment by takumiya081** [comment]
thank you!!
