### ISSUE TITLE
bug: Definition for rule 'no-unreachable-types' was not found 

### ISSUE THREAD

**Issue by dnalborczyk** [dotansimha/graphql-eslint#267]
version: **0.7.1**

I believe the file is not being exported: https://github.com/dotansimha/graphql-eslint/blob/%40graphql-eslint/eslint-plugin%400.7.1/packages/plugin/src/rules/index.ts

a doc reference seems to be missing in the rules overview as well.

I'll try to put up a PR: https://github.com/dotansimha/graphql-eslint/pull/268

**Comment by dotansimha** [comment]
Thank you @dnalborczyk , will release a new version in a few minutes :)

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@0.7.2` :)

**Comment by dnalborczyk** [comment]
thank you @dotansimha !!
