### ISSUE TITLE
bug: `no-unreachable-types` does not recognize implemented interfaces

### ISSUE THREAD

**Issue by dnalborczyk** [dotansimha/graphql-eslint#273]
version: **v0.7.2**

repro:

```graphql
interface Foo {
  foo: String
}

type FooBar implements Foo {
  foo: String
}

type Query {
  getFoo: FooBar
}
```

throws:
`error  Type "Foo" is unreachable  @graphql-eslint/no-unreachable-types`

test case PR: https://github.com/dotansimha/graphql-eslint/pull/274

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@0.8.0`
