### ISSUE TITLE
Getting Javascript heap out of memory on a project with 200+ .graphql files

### ISSUE THREAD

**Issue by joual** [dotansimha/graphql-eslint#281]
We're currently on 0.4.2 and anything 5.x+ above yields the following after a while. It's also much slower.

```
<--- Last few GCs --->

[24472:0x102d75000]   306785 ms: Mark-sweep 2023.8 (2052.1) -> 2023.7 (2052.3) MB, 1474.0 / 0.0 ms  (average mu = 0.130, current mu = 0.043) allocation failure scavenge might not succeed
[24472:0x102d75000]   307875 ms: Mark-sweep 2024.3 (2052.6) -> 2023.4 (2052.3) MB, 1088.5 / 0.0 ms  (average mu = 0.079, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x100a02a19]
    1: StubFrame [pc: 0x1009e301f]
Security context: 0x1d6de70408d1 <JSObject>
    2: split [0x1d6de704cd51](this=0x1d6daea94379 <String[46]\: \n  Get list of analyze views of this survey\n  >,0x1d6daea94399 <JSRegExp <String[#11]: \r\n|[\n\r]>>)
    3: readBlockString(aka readBlockString) [0x1d6d1f766d19] [/Users/joelm/dev/webplatform/smweb/node_modules/graphql/language/lexer.js:~573] [pc=0x2b01f005cf8e...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1011f40c5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a5749 node::Abort() [/usr/local/bin/node]
 3: 0x1000a58af node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001eddb7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001edd57 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x1003848f5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10038614a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x100382bce v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x100380980 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x10038c7aa v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x10038c831 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x10035a9aa v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
13: 0x1006aa1d8 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x100a02a19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
15: 0x1009e301f Builtins_RegExpSplit [/usr/local/bin/node]
```

**Comment by dotansimha** [comment]
Hi @joual ! 
Can you please share more information? How do you use it? how does your settings looks like? Is it possible for you to create a reproduction of the issue?

**Comment by joual** [comment]
We use it in a monorepo of express apps. We have a .graphrc in each app with the content:

```
schema: '../../api/graphapi/lib/graphql-schema.graphql'
```

Our eslint config uses an override for .graphql files, which contain our queries:

```
  overrides: [
    {
      files: ['apps/**/*.graphql'],
      excludedFiles: ['apps/smadminweb/**/*.graphql'],
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint', 'smweb-graphql-rules'],
      rules: {
        '@graphql-eslint/require-id-when-available': ['warn'],
        '@graphql-eslint/validate-against-schema': [
          'error',
          { disableRules: ['KnownFragmentNames', 'NoUnusedFragments'] },
        ],
      },
    },
    {
      files: ['apps/smadminweb/**/*.graphql'],
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint'],
      rules: {}, // empty but the idea is that .graphql files get parsed
    },
```

**Comment by joual** [comment]
Unfortunately I'm not sure I can provide a reproduction repository without copying a lot of protected code :S 

I understand this is fairly opaque in terms of capability to debug, so this is mainly for tracking in case someone else runs into this. I'll try to debug this a little bit more later.

**Comment by dotansimha** [comment]
Got it, thank you for the additional details, @joual . I will try to reproduce and improve that. 
I assume it might have something to do with the parserOptions and the way it loads the schema. Btw, are you using the latest version of this package? Because we recently did some performance improvements.

**Comment by alias-mac** [comment]
I'm running to a similar issue, but 2 main differences:
- it is taking a long time to process data, but eventually finishes
- I have `gql` in TypeScript files.

I also have protected code that I can't share. Leaving information here in case it helps others.

**Comment by Urigo** [comment]
thanks for the new info @alias-mac 

Do you think any of you could create a reproduction with sample files (just many of these....) to see if you get to reproduce it?

That would really help us push this issue forward through out [new issue phases](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)

(also more info [here](https://the-guild.dev/blog/oss-contributor-workflow))

**Comment by dotansimha** [comment]
We've just released `v1.0.0`, with dependencies updates and some caching improvements. @alias-mac let me know if you see some improvement :)

**Comment by alias-mac** [comment]
@dotansimha, I tested with version 0.9.x and 1.x and no big difference in execution time.
For 0.9.x:
```
Done in 34.31s.
```
For 1.x:
```
Done in 33.77s.
```

For comparison, without graphql files it takes less than 7 seconds:
```
Done in 6.54s.
```

**Comment by dotansimha** [comment]
@B2o5T pushed some fixes in https://github.com/dotansimha/graphql-eslint/pull/511 , that should improve that, let's give it a try with next release ;)

**Comment by dotansimha** [comment]
Please try `@graphql-eslint/eslint-plugin@1.1.3`
