### ISSUE TITLE
Conflict with @typescript-eslint/recommended-requiring-type-checking

### ISSUE THREAD

**Issue by jgoux** [dotansimha/graphql-eslint#288]
Hello,

I enabled `@typescript-eslint/recommended-requiring-type-checking` which requires tsc behind the scene and it seems that the processor part of graphql-eslint in my overrides array is not working with it.

Here is the error : 
```
Error: Error while loading rule '@typescript-eslint/non-nullable-type-assertion-style': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /Users/admin/Documents/Code/Clovis-team/clovis-labs/clovis/src/client/screens/App/Organization/Project/Task/Task.tsx/0_document.graphql
```

And here is my eslint configuration : 
```js
module.exports = {
  env: {
    browser: true,
    es6: true,
    jest: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:prettier/recommended",
    "plugin:react/recommended",
    "plugin:sonarjs/recommended",
    "plugin:testing-library/recommended",
    "plugin:testing-library/react",
    "plugin:jest-dom/recommended",
  ],
  "ignorePatterns": ["/*.*", "src/**/generated/*", "src/**/*.graphql.ts"],
  overrides: [
    {
      files: ["*.tsx", "*.ts"],
      processor: "@graphql-eslint/graphql",
    },
    {
      files: ["*.graphql"],
      parser: "@graphql-eslint/eslint-plugin",
      plugins: ["@graphql-eslint"],
      rules: {
        "prettier/prettier": "off",
      },
    },
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "./tsconfig.json",
    tsconfigRootDir: __dirname,
  },
  plugins: [
    "@typescript-eslint",
    "prettier",
    "simple-import-sort",
    "import",
    "sort-keys-fix",
    "sort-destructure-keys",
    "sonarjs",
    "testing-library",
    "jest-dom",
  ],
  root: true,
  rules: {
    "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/non-nullable-type-assertion-style": "error",
    "@typescript-eslint/prefer-nullish-coalescing": "error",
    "@typescript-eslint/prefer-optional-chain": "error",
    "@typescript-eslint/prefer-ts-expect-error": "error",
    "@typescript-eslint/switch-exhaustiveness-check": "error",
    "import/first": "error",
    "import/newline-after-import": "error",
    "import/no-duplicates": "error",
    "react/react-in-jsx-scope": "off",
    "simple-import-sort/exports": "error",
    "simple-import-sort/imports": "error",
    "sort-destructure-keys/sort-destructure-keys": "error",
    "sort-imports": "off",
    "sort-keys-fix/sort-keys-fix": "error",
  },
  settings: {
    react: {
      version: "detect",
    },
  },
};

```

As you can see I already specified the `parserOptions.project` so I'm not sure what to do now. 😅 

If I comment all the `recommended-requiring-type-checking` rules and the plugin, graphql-eslint is working : 
```js
module.exports = {
  env: {
    browser: true,
    es6: true,
    jest: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    // "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:prettier/recommended",
    "plugin:react/recommended",
    "plugin:sonarjs/recommended",
    "plugin:testing-library/recommended",
    "plugin:testing-library/react",
    "plugin:jest-dom/recommended",
  ],
  "ignorePatterns": ["/*.*", "src/**/generated/*", "src/**/*.graphql.ts"],
  overrides: [
    {
      files: ["*.tsx", "*.ts"],
      processor: "@graphql-eslint/graphql",
    },
    {
      files: ["*.graphql"],
      parser: "@graphql-eslint/eslint-plugin",
      plugins: ["@graphql-eslint"],
      rules: {
        // "eol-last": "off",
        "prettier/prettier": "off",
      },
    },
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "./tsconfig.json",
    tsconfigRootDir: __dirname,
  },
  plugins: [
    "@typescript-eslint",
    "prettier",
    "simple-import-sort",
    "import",
    "sort-keys-fix",
    "sort-destructure-keys",
    "sonarjs",
    "testing-library",
    "jest-dom",
  ],
  root: true,
  rules: {
    // "@typescript-eslint/consistent-type-imports": "error",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    // "@typescript-eslint/non-nullable-type-assertion-style": "error",
    // "@typescript-eslint/prefer-nullish-coalescing": "error",
    // "@typescript-eslint/prefer-optional-chain": "error",
    // "@typescript-eslint/prefer-ts-expect-error": "error",
    // "@typescript-eslint/switch-exhaustiveness-check": "error",
    "import/first": "error",
    "import/newline-after-import": "error",
    "import/no-duplicates": "error",
    "react/react-in-jsx-scope": "off",
    "simple-import-sort/exports": "error",
    "simple-import-sort/imports": "error",
    "sort-destructure-keys/sort-destructure-keys": "error",
    "sort-imports": "off",
    "sort-keys-fix/sort-keys-fix": "error",
  },
  settings: {
    react: {
      version: "detect",
    },
  },
};

```

I'm using the `v0.7.2` 👍

**Comment by dotansimha** [comment]
Hi @jgoux ! 
I tried to reproduce this in another project, but couldn't get the same error. Any chance you can share a minimal reproduction?
Also, can you please try to run it without the `processor`? Or change the order of the `overrides`?

**Comment by jgoux** [comment]
Hey @dotansimha 😃 

> can you please try to run it without the processor?
When the processor part is removed, I have no error. But as you can guess, my gql template tags aren't picked up.

> Or change the order of the overrides
When I have the processor block in last position in the overrides array, I have the exact same error.

Here is a minimal reproduction : https://codesandbox.io/s/graphql-eslint-bug-froc0

Open a terminal and fire `yarn lint` 👍

**Comment by dotansimha** [comment]
I think you have a conflict with `root` and `overrides` here. Can you please try this configuration? 

```js
module.exports = {
  overrides: [
    {
      files: ["*.tsx", "*.ts"],
      processor: "@graphql-eslint/graphql",
    },
    {
      files: ["*.graphql"],
      parser: "@graphql-eslint/eslint-plugin",
      plugins: ["@graphql-eslint"],
      rules: {
        "prettier/prettier": "off",
      },
    },
    {
      env: {
        browser: true,
        es6: true,
      },
      parser: "@typescript-eslint/parser",
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: __dirname,
      },
      plugins: ["@typescript-eslint", "prettier"],
      settings: {
        react: {
          version: "detect",
        },
      },
      extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:prettier/recommended",
      ],
      files: ["**/*.ts", "**/*.tsx"],
    },
  ],
};

```

**Comment by jgoux** [comment]
I updated the sandbox with the proposed configuration and the error is gone.

Is there any downside writing it this way and omiting the root property?

Also, while the error is gone, it doesn't seem to lint my fragment in `pages/index.ts`. I purposely made a typo on the `name` field to test.

**Comment by dotansimha** [comment]
@jgoux

> I updated the sandbox with the proposed configuration and the error is gone.
> 
> Is there any downside writing it this way and omiting the root property?

No down side, but when you use `root` - it enforces the setup on the root for all sub-configurations, leading to conflicts when you have more than 1 parser active.

> Also, while the error is gone, it doesn't seem to lint my fragment in `pages/index.ts`. I purposely made a typo on the `name` field to test.

I think your command it running eslint for specific files, right? can you try to add `.graphql` extension as well? (to the eslint command).
You should be able to get this working with added rules, and also - you can remove `prettier/prettier` disable command since we already fixed that in latest versions :) 


> EDIT : I realize that there isn't a `recommended` set of rules, so maybe I have to activate each rules individually?
> 
> It would be great to have a `recommended` set of rules to enforce best practices. At least I was expecting to have the same errors as the VSCode Graphql extension gives me. I saw that there was a validation-against-schema rule but as it's deprecated it's quite tedious to compose my own ruleset, I always prefer following standards. 😄

Not yet, but I do want to collect the recommend ones and make an "official" recommended set. The thing is - I don't want to force users to provide `schema` or `operations`, and without these - the set of recommended rules won't be effective. 



> Right now I'm using the deprecated `validation-against-schema` because it's working fine.

I'm thinking about leaving it - the thing is that is requires some adjustments per each project, that's why I separated it.

**Comment by jgoux** [comment]
@dotansimha 

> Not yet, but I do want to collect the recommend ones and make an "official" recommended set. The thing is - I don't want to force users to provide schema or operations, and without these - the set of recommended rules won't be effective.

Maybe you could do like typescript-eslint and provide both experiences : 
- `@graphql-eslint/recommended`
- `@graphql-eslint/recommended-requiring-schema`

So people can opt-in later to have the full awesomeness! 😄 

Anyway, it's now working, thanks *a lot* for the help, and I can't wait for the `recommanded` rules. 😍 

Have a great day. 🌞

**Comment by dotansimha** [comment]
> @dotansimha
> 
> > Not yet, but I do want to collect the recommend ones and make an "official" recommended set. The thing is - I don't want to force users to provide schema or operations, and without these - the set of recommended rules won't be effective.
> 
> Maybe you could do like typescript-eslint and provide both experiences :
> 
> * `@graphql-eslint/recommended`
> * `@graphql-eslint/recommended-requiring-schema`
> * `@graphql-eslint/recommended-requiring-operations`
> 
> So people can opt-in later to have the full awesomeness! 😄
> 
> Anyway, it's now working, thanks _a lot_ for the help, and I can't wait for the `recommanded` rules. 😍
> 
> Have a great day. 🌞

Awesome, happy to hear that everything works now :) Btw, feel free to share your recommended set of rules here, it could really help us to understand other people’s use-cases!

**Comment by jgoux** [comment]
Right now I'm only using : 

```
// Avoid issues with graphql-codegen
 "@graphql-eslint/no-anonymous-operations": "error",
// Avoid typos
"@graphql-eslint/validate-against-schema": "error"
```

This is purely technical, I don't enforce any conventions. I'll probably do it in the future when Hasura will provide conventional names to its generated GraphQL API. 😜

Also I opened an issue on the VSCode GraphQL extension now that this plugin is able to provide the same validation guarantees and more : https://github.com/graphql/vscode-graphql/issues/280

**Comment by scherroman** [comment]
This had me confused and unable to get the plugin to work without digging into the repo issues, as while the setup instructions say to put your `@graphql-eslint` configuration under the `overrides` section, it doesn't mention the need put/move the rest of your existing top-level eslint configuration under the overrides section as well to avoid conflicts. 

In any case, works like a charm now, `require-id-when-available` is awesome and essential imo to avoid accidental nasty hidden bugs in your app when using the apollo-client normalized cache
