### ISSUE TITLE
Version 0.8.0 needs graphql@15.5.0 (?)

### ISSUE THREAD

**Issue by eddeee888** [dotansimha/graphql-eslint#293]
## Bug description

Version 0.8.0 comes with this commit: https://github.com/dotansimha/graphql-eslint/commit/2f6313b5b712715e3516c85c9a5d97e4719795d6 which depends on the rules to be in the `graphql` package. However, the rules have only been renamed to have `Rule` suffix in this PR: https://github.com/graphql/graphql-js/pull/2402 which is graphql@15.0.0

As a result, when I tried to run `graphql-eslint` with graphql@14.6.0, it failed because the rule file name is different.

Bumping to graphql@15.5.0 solved this issue for me.

## Suggestions

Maybe we can update the `peerDependencies` to reflect this? ( I think that's what it's for right? ) 
Or maybe we could revert the commit that sets external rules for now? :)

**Comment by dotansimha** [comment]
Hi @eddeee888 
Tracking this in https://github.com/dotansimha/graphql-eslint/issues/292 
It was a mistake, we fixed a bundling issue in the package, and now the graphql-js validation rules comes from `node_modules`, leading to an error in case of a new version of graphql. 
Working on a fix :)

**Comment by dotansimha** [comment]
I tried to fix that in https://github.com/dotansimha/graphql-eslint/pull/298 . can you please try the alpha version? `@graphql-eslint/eslint-plugin@0.8.1-alpha-7440aa7.0`

**Comment by eddeee888** [comment]
It's working on my end. Cheers! 🎉

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@0.8.1`
