### ISSUE TITLE
Documentation does not specify if rules are enabled by default

### ISSUE THREAD

**Issue by therealgilles** [dotansimha/graphql-eslint#299]
I cannot find any information about whether rules are enabled by default or not. It would be good to clarify.

**Comment by dotansimha** [comment]
Hi! We have in our README: `This repo doesn't exports a "recommended" set of rules - feel free to recommend us!`

 (https://github.com/dotansimha/graphql-eslint#available-rules)

But I'll update it to be more clear. Thanks @therealgilles !
