### ISSUE TITLE
New rule: Strict id in types in schema

### ISSUE THREAD

**Issue by eddeee888** [dotansimha/graphql-eslint#326]
**Is your feature request related to a problem? Please describe.**

This is a feature request for a new rule that targets schema files.

I think when it comes to GraphQL schema design, things that are domain models e.g. `User`, `Post`, `Comment` should always have a field with name `id` and type `ID` in the schema ( these are normally the `id` in the database ). This will help caching according to the [GraphQL spec](https://spec.graphql.org/June2018/#sec-ID)

For result payload types or types that do not have a natural id field such as pagination, it is fine not to have an id.

**Describe the solution you'd like**

It would be good to have a new rule `strict-id-types-in-schema` ( open for name suggestions )

This rule should:

- enforce types to have a field with an `ID` type
- look for an `id` field with `ID` type by default. The name of the field could be changed to other values e.g. `key`
- have an ability to exclude object types that have certain suffix/prefix e.g. `Result`, `Payload`, `Pagination`

**Describe alternatives you've considered**

I've looked at all the existing rules but can't find any that specifically targets `id` fields on the schema

**Additional context**

Happy to put together a PR if this sounds like a good rule :)

**Comment by dotansimha** [comment]
Thank you for reporting this @eddeee888 . This sounds like a fairly custom behavior, but we do follow this kind of structure in our GraphQL projects, so it might make sense to others as well. 
I guess as long as it's easily customizable - this could be a great rule :) PRs are always welcome!

**Comment by eddeee888** [comment]
Hi @dotansimha , this is implemented in https://github.com/dotansimha/graphql-eslint/pull/333. Please have a look when you have a chance 🙏

**Comment by dotansimha** [comment]
Awesome work, @eddeee888 . Thank you! 
It's availble now in `@graphql-eslint/eslint-plugin@0.9.0`.
