### ISSUE TITLE
Wonky package text description in VS Code

### ISSUE THREAD

**Issue by bradleyayers** [dotansimha/graphql-eslint#328]
**Describe the bug**

When hovering the version string in a `package.json` in VS Code it shows a text description of the package, but for this package it includes HTML tags for images.

This is just a nitpick, but helps add to the confidence in the package when little details like this are taken care of.

![image](https://user-images.githubusercontent.com/105820/108639259-b94c8800-74e7-11eb-9ea6-20912294d90c.png)

**Expected behavior**

I'd expect the `<img>` tags not to be there.

**Environment:**

- OS: macOS
- `@graphql-eslint/...`: 0.8.0
- NodeJS: n/a

**Additional context**

**VS Code:**
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by dotansimha** [comment]
Thanks @bradleyayers ! 
I'll update the README, next release should be fine!

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@0.8.1`
