### ISSUE TITLE
IntelliJ IDEA and WebStorm do not visualizes lint issues

### ISSUE THREAD

**Issue by mcohen75** [dotansimha/graphql-eslint#359]
**Describe the bug**
IntelliJ IDEA and WebStorm do not visualizes lint issues.

**To Reproduce**
1. Run `npm install` in any one of the example project directories.
2. Open the example project in IDEA or WebStorm.
3. Configure to use Automatic ESLint Configuration (Languages & Frameworks -> JavaScript -> Code Quality Tools -> ESLint)
4. Probably restart IDEA/WebStorm

**Expected behavior**
ESLint rule violations are visible in the normal way.

**Environment:**

- OS: macOS 10.16
- `@graphql-eslint/...`:0.8.0
- NodeJS: tried with v10.24.0 and 12.21.0

Details from about screen:
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 25, 2021
Licensed to Indeed / Mike Cohen
Subscription is active until November 5, 2021.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12

**Additional context**
When running eslint at the terminal all works fine. e.g. in the sample project `npm run lint`. Rule violations are found and printed out in the normal way.

I noticed that the README suggests that this should work in WebStorm:
"Integrates and visualizes lint issues in popular IDEs (VSCode / WebStorm)" ​

I logged a bug with IntelliJ here:
https://youtrack.jetbrains.com/issue/WEB-49805

A support rep responded indicating that they are able to reproduce the problem I saw.

WebStorm has a new feature in EAP that allows you to specify a glob to determine which files ESLint should be run against. I tried using this but saw the same results (see the IntelliJ ticket for the version and a download link).

**Comment by rtrembecky** [comment]
Hello, I've experienced the issue of ESLint not highlighting the code issues too, but in VSCode. I played with different settings and these are my findings (hopefully you'll find something relevant for IntelliJ as well):
- I needed **some** VSCode extension for handling GraphQL installed
  - installing either https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql or https://marketplace.visualstudio.com/items?itemName=mquandalle.graphql worked to let VSCode know it should care about `.graphql` files
  - I was not able to make ESLint work with via any options (`eslint.validate`, `eslint.options`, `eslint.probe`) without this
- I needed `"graphql"` in `"eslint.validate"` config array in VSCode's `setting.json`

**Comment by rtrembecky** [comment]
It may be a good idea to update the README on the need for some other IDE GraphQL extension, provided I'm right on this.

**Comment by B2o5T** [comment]
@rtrembecky I think this is a good idea to inform in README that in order to show eslint errors in graphql files the user must have installed GraphQL extension for syntax highlighting, I tested on my VSCode, and without this extension, I can't see eslint errors 👍
Same for me I don't need to provide  `".gql", ".graphql"` in `extentions` of `eslint.options`, I think it can be removed

I only need to provide `"graphql"` in `"eslint.validate"`

Can you make PR ?

**Comment by rtrembecky** [comment]
@B2o5T I believe you wrote a comment here and then deleted it. However, I created a PR as you suggested: #491

**Comment by B2o5T** [comment]
> @B2o5T I believe you wrote a comment here and then deleted it. However, I created a PR as you suggested: #491

It's amazing ! Thank you! Yes, you are right I posted a comment, and after I deleted it because I saw that it's an offtopic comment and he's not relevant to IDEA issue 🙂

**Comment by rtrembecky** [comment]
Yeah, maybe I should've really created a separate issue for this... 🤦

**Comment by mcohen75** [comment]
It looks as though this has been fixed in the latest IntelliJ IDEA EAP build. 2021.2 EAP build 212.4535.15, released June 29, 2021.

**Comment by B2o5T** [comment]
I confirm that this was fixed. I use WebStorm 2021.2.1

![image](https://user-images.githubusercontent.com/7361780/134158467-99f579c8-84f9-4011-836b-20f6c3a2c419.png)
