### ISSUE TITLE
Support multiple id field names in require-id-when-available

### ISSUE THREAD

**Issue by dobesv** [dotansimha/graphql-eslint#382]
**Is your feature request related to a problem? Please describe.**

We support two identifier fields for the apollo cache - `_id` and `id`.  It would be great if the linter could check that if either of these fields is in the schema it will be used.  Currently you can only check for one field name with this rule.

I think this could be a matter of changing the code at https://github.com/dotansimha/graphql-eslint/blob/master/packages/plugin/src/rules/require-id-when-available.ts#L83 so that instead of considering only the first option, it loops over the options.

**Comment by B2o5T** [comment]
hi @dobesv, please try `3.1.0-alpha-878c908.0` alpha version and give your feedback

**Comment by dotansimha** [comment]
Available in `@graphql-eslint/eslint-plugin@3.2.0`.
