### ISSUE TITLE
NoUnusedVariablesRule error when a variable is not used if it is used in a fragment but not the operation itself

### ISSUE THREAD

**Issue by dobesv** [dotansimha/graphql-eslint#384]
**Describe the bug**

The linter will complain that a variable is not used if it is used in a fragment but not the operation itself.

**To Reproduce**

```
fragment OrgFragment on Org {
  _id
  descendants @include(if: $includeDescendants) {
    _id
    name
    parent {
      _id
    }
    type
  }
  name
  parent {
    _id
  }
  type
}

query OrgsQuery($includeDescendants: Boolean!) {
  viewer {
    _id
    orgs {
      roles
      org {
        ...OrgFragment
      }
      verified
    }
  }
}
```

```
 20:18  error  [NoUnusedVariablesRule] Variable "$includeDescendants" is never used in operation "OrgsQuery"     @graphql-eslint/validate-against-schema
```

**Comment by B2o5T** [comment]
`validate-against-schema` rule is deprecated

**Comment by dotansimha** [comment]
As @B2o5T said, we deprecated (and will remove in v1) the `validate-against-schema` since it's complex to run as a complete suite, like `graphql-js` does. We broke each ValidationRule to have it's own graphql-eslint rule, to make it easier to manage the exact output.
