### ISSUE TITLE
`loadSiblings()` returns incorrect `location` (filePath)

### ISSUE THREAD

**Issue by B2o5T** [dotansimha/graphql-eslint#412]
**Describe the bug**

`loadSiblings()` returns incorrect `location`'s
https://github.com/dotansimha/graphql-eslint/blob/master/packages/plugin/src/sibling-operations.ts#L53

It's join `baseDir` path with `location`, but `location` already contains `baseDir` path

**To Reproduce**

Make console.log 
```js
const siblingFragments = siblings.getFragment(fragmentName)
```
And you will see incorrect `filePath`, there is duplication of my baseDir `/Users/dimitri/Desktop/pickpacknship/packages/my-wing`
```js
{
    filePath: '/Users/dimitri/Desktop/pickpacknship/packages/my-wing/Users/dimitri/Desktop/pickpacknship/packages/my-wing/src/gql/queries/Collects.gql',
    document: {
      kind: 'FragmentDefinition',
...
```

**Environment:**

- `@graphql-eslint/...`: v0.9.1
- NodeJS: v14.16.0

**Comment by dotansimha** [comment]
Fixed in `v1.0.0`! 🎉
