### ISSUE TITLE
Prettier on virtual documents generated by processor

### ISSUE THREAD

**Issue by xeladejo** [dotansimha/graphql-eslint#421]
**Describe the bug**

Codefile with GraphQL operations:
```typescript
import { gql } from "apollo-server-core";

export const OPERATION = gql`
    query operation($id: ID!) {
        operation(id: $id) {
            id
        }
    }
`;
```

Prettier try to convert it to:
```typescript
import { gql } from "apollo-server-core";

export const OPERATION = gql`query operation($id: ID!) {
    operation(id: $id) {
        id
    }
}`;
```

**To Reproduce**

.prettierrc.json
```json
{
  "printWidth": 120,
  "overrides": [
    {
      "files": "*.graphql",
      "options": {
        "parser": "graphql"
      }
    }
  ]
}
```

.eslintrc.json
```json
{
  "root": true,
  "extends": [
    "eslint:recommended",
    "plugin:prettier/recommended"
  ],
  "processor": "@graphql-eslint/graphql",
  "overrides": [
    {
      "files": ["*.graphql"],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      "rules": {
        "@graphql-eslint/require-id-when-available": ["error"]
      }
    }
  ]
}
```

**Expected behavior**

Keep codefile with GraphQL operations:
```typescript
import { gql } from "apollo-server-core";

export const OPERATION = gql`
    query operation($id: ID!) {
        operation(id: $id) {
            id
        }
    }
`;
```

**Environment:**

- OS: Linux 5.10.34-1-lts
- `@graphql-eslint/...`: 0.9.1
- NodeJS: 14.16.0

**Additional context**

I will try to explain what I think is happening adding new line characters `\n` to the document:
```typescript
import { gql } from "apollo-server-core";\n
\n
export const OPERATION = gql`\n
    query operation($id: ID!) {\n
        operation(id: $id) {\n
            id\n
        }\n
    }\n
`;\n
```

The `@graphql-eslint/eslint-plugin` processor extract from "gql\`" to "\`;" so the generated virtual document begin with a new line:
```graphql
\n
query operation($id: ID!) {\n
    operation(id: $id) {\n
        id\n
    }\n
}\n
```

I think is better extract from "gql\`\n" to "\`;" if the `\n` exists and my assumptions are correct...

**Comment by Urigo** [comment]
Hi @xeladejo and thank you for the report!

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems like we are really close to getting this issue into `stage 1`.
In order to do that, would you be able to put your code into code sandbox and a repo we could easily run and reproduce?

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by xeladejo** [comment]
I hope this can help: https://github.com/xeladejo/eslint-graphql

```
git clone https://github.com/xeladejo/eslint-graphql.git
cd eslint-graphql
npm install
npm run lint
```

**Comment by B2o5T** [comment]
Hi @xeladejo 

There is no issue with `graphql-eslint`
Your `eslint` config is wrong, you must specify `"processor": "@graphql-eslint/graphql"` only on `js`, `ts` files, same for `"plugin:prettier/recommended"` in extends array

```diff
{
  "root": true,
  "ignorePatterns": ["dist"],
  "parserOptions": {
    "ecmaVersion": 2020
  },
- "extends": [
-  "eslint:recommended",
-  "plugin:prettier/recommended"
- ],
+ "extends": ["eslint:recommended"],
- "processor": "@graphql-eslint/graphql",
  "env": {
    "node": true
  },
  "rules": {
    "no-console": ["warn"],
    "no-duplicate-imports": ["error"],
    "sort-imports": ["error", { "ignoreDeclarationSort": true }]
  },
  "overrides": [
    {
      "files": ["*.ts"],
      "parser": "@typescript-eslint/parser",
      "parserOptions": {
        "project": "./tsconfig.json"
      },
+     "processor": "@graphql-eslint/graphql",
      "plugins": ["@typescript-eslint"],
-     "extends": ["plugin:@typescript-eslint/recommended"],
+     "extends": ["plugin:@typescript-eslint/recommended", "plugin:prettier/recommended"],
      "rules": {
        "@typescript-eslint/explicit-function-return-type": ["error", { "allowExpressions": true }],
        "@typescript-eslint/explicit-member-accessibility": ["error"],
        "@typescript-eslint/member-ordering": ["error"],
        "@typescript-eslint/no-use-before-define": ["error", { "functions": false }],
        "@typescript-eslint/promise-function-async": ["error"],
        "@typescript-eslint/require-await": ["error"]
      }
    },
    {
      "files": ["*.graphql"],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      "rules": {
        "@graphql-eslint/require-id-when-available": ["error"]
      }
    }
  ]
}
```

So this changes give me no problems

**Comment by xeladejo** [comment]
You are right, with those changes I don't get prettier errors on virtual documents. But then the schemas `*.graphql` are not prettified. See last commit: https://github.com/xeladejo/eslint-graphql

As collateral damage the `*.js` configurations as `graphql.config.js` are not prettified.

And finally if there are errors in the virtual documents the eslint reports indicate wrong line:

```typescript
import { gql } from "apollo-server";

export const NUMERIC = gql`
    query numeric($id: ID!) {
        numeric(id: $id) {
            id
              one
            two
        }
    }
`;
```

```
src/operations/numeric.ts
  0:13  error  Delete `····`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by B2o5T** [comment]
I think you totally right, there is a problem with `@graphql-eslint/graphql` processor
![image](https://user-images.githubusercontent.com/7361780/118367075-2fb9cd00-b5a1-11eb-89a3-92f0256e09e8.png)
`source` and `prettierSource` are different in `eslint-plugin-prettier` after adding `processor: '@graphql-eslint/graphql'` in override config
after changing this line https://github.com/dotansimha/graphql-eslint/blob/master/packages/plugin/src/processors/code-files.ts#L29 to `skipIndent: false` i also have 2 prettier errors
```sh
/Users/dimitri/Desktop/eslint-prettier/src/operations/alphabetical.ts
  9:2  error  Insert `⏎`  prettier/prettier

/Users/dimitri/Desktop/eslint-prettier/src/operations/numeric.ts
  9:2  error  Insert `⏎`  prettier/prettier

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```
This is because there is no `\n` character on the end
![image](https://user-images.githubusercontent.com/7361780/118368213-267d3000-b5a2-11eb-946f-8a032d06dfcb.png)
So the problem is in `@graphql-tools/graphql-tag-pluck` as it's parse code differently than prettier

**Comment by B2o5T** [comment]
So I found I way, when you add `processor: '@graphql-eslint/graphql'` in your config than `eslint-plugin-prettier` will parse the source code (example file with filepath `/Users/dimitri/Desktop/eslint-prettier/src/operations/alphabetical.ts`)

But also he will parse [extracted documents code](https://github.com/dotansimha/graphql-eslint/blob/master/packages/plugin/src/processors/code-files.ts#L36) for this file and for first extracted document filepath will be `/Users/dimitri/Desktop/eslint-prettier/src/operations/alphabetical.ts/0_document.graphql` where 0 is number of extracted documents minus one, for second extracted document from this file filepath will be `/Users/dimitri/Desktop/eslint-prettier/src/operations/alphabetical.ts/1_document.graphql`.

So how can we fix that?
We cannot add `*_document.graphql` to `.prettierignore` as it's file is virtual and don't really exists on disk
To fix this we need to override `eslint` config for `prettier/prettier rule`
```js
  {
    files: ['*_document.graphql'],
    rules: {
      'prettier/prettier': 'off',
    },
  }
```

**Comment by B2o5T** [comment]
@xeladejo try this eslint config for lint `js`, `ts` and `graphql` files, and tell me if it works as you expect
```js
const rules = {
  'no-console': ['warn'],
  'no-duplicate-imports': ['error'],
  'sort-imports': ['error', { ignoreDeclarationSort: true }],
};

module.exports = {
  root: true,
  ignorePatterns: ['dist'],
  parserOptions: {
    ecmaVersion: 2020,
  },
  env: {
    node: true,
  },
  overrides: [
    {
      files: ['*.js'],
      extends: ['eslint:recommended', 'plugin:prettier/recommended'],
      rules,
    },
    {
      files: ['*.ts'],
      parser: '@typescript-eslint/parser',
      parserOptions: {
        project: './tsconfig.json',
      },
      processor: '@graphql-eslint/graphql',
      extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended', 'plugin:prettier/recommended'],
      rules: {
        ...rules,
        '@typescript-eslint/explicit-function-return-type': ['error', { allowExpressions: true }],
        '@typescript-eslint/explicit-member-accessibility': ['error'],
        '@typescript-eslint/member-ordering': ['error'],
        '@typescript-eslint/no-use-before-define': ['error', { functions: false }],
        '@typescript-eslint/promise-function-async': ['error'],
        '@typescript-eslint/require-await': ['error'],
      },
    },
    {
      files: ['*.graphql'],
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint'],
      extends: ['plugin:prettier/recommended'],
      rules: {
        '@graphql-eslint/require-id-when-available': ['error'],
      },
    },
    {
      files: ['*_document.graphql'],
      rules: {
        'prettier/prettier': 'off',
      },
    },
  ],
};
```

**Comment by xeladejo** [comment]
Yeah, that seems to work fine.

If it were possible to use `--fix` in the problems detected in virtual documents it would be perfect.

Thanks you.
