### ISSUE TITLE
Processor `@graphql-eslint/graphql` might fail to process due to GraphQL comments. 

### ISSUE THREAD

**Issue by lukaskl** [dotansimha/graphql-eslint#422]
**Intro**
Not sure if this is really  `graphql-eslint` or `graphql-tag-pluck` issue, but I've found a clear reproducible case using this repository, so I thought, I'll report it here. Also, [I've made a repository](https://github.com/lukaskl/graphql-eslint-parse-issue) where the issue is reproducible. 

**Describe the bug**

It seems that if `processor: '@graphql-eslint/graphql'` option is used together with `.graphql` or `.gql` files and if those files contain comments, processor might fail to process the file.

E.g.

- This one is processed without any issues:
  ```gql
  fragment UserFields on User {
    id
    name
  }
  ```
- This one is processed as well without any issues:
  ```gql
  # Just any comment without any other file mentions
  fragment UserFields on User {
    id
    name
  }
  ```
- This file fails:
  ```gql
  # Lets mention another file, e.g.: User1.fragment.gql in this comment
  fragment UserFields on User {
    id
    name
  }
  ```

**To Reproduce**

Use this repository: https://github.com/lukaskl/graphql-eslint-parse-issue
```
git clone git@github.com:lukaskl/graphql-eslint-parse-issue.git
cd graphql-eslint-parse-issue
yarn install --frozen-lockfile
yarn eslint .
``` 

**✅ Expected result**

The output should be something like this:
```
➜  graphql-eslint-parse-issue yarn eslint .
yarn run v1.15.2

***/src/User0.fragment.gql
  3:4  warning  This field is marked as deprecated in your GraphQL schema (reason: Use `firstName` instead.)  @graphql-eslint/no-deprecated

***/src/User1.fragment.gql
  4:4  warning  This field is marked as deprecated in your GraphQL schema (reason: Use `firstName` instead.)  @graphql-eslint/no-deprecated

***/src/User2.fragment.gql
  4:4  warning  This field is marked as deprecated in your GraphQL schema (reason: Use `firstName` instead.)  @graphql-eslint/no-deprecated

✖ 3 problems (0 errors, 3 warnings)
```

**🔴 Actual result**

```
➜  graphql-eslint-parse-issue yarn eslint .
yarn run v1.15.2
$ ***/node_modules/.bin/eslint .
[graphql-eslint/processor]: Unable to process file "***/src/User2.fragment.gql":  SyntaxError: Unexpected token (1:0)
    at Object._raise (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:776:17)
    at Object.raiseWithData (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:769:17)
    at Object.raise (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:737:17)
    at Object.unexpected (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:9253:16)
    at Object.parseExprAtom (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:10743:20)
    at Object.parseExprAtom (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:4996:20)
    at Object.parseExprSubscripts (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:10318:23)
    at Object.parseUpdate (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:10298:21)
    at Object.parseMaybeUnary (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:10276:23)
    at Object.parseExprOps (***/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:10141:23) {
  loc: Position { line: 1, column: 0 },
  pos: 0
}

***/src/User0.fragment.gql
  3:4  warning  This field is marked as deprecated in your GraphQL schema (reason: Use `firstName` instead.)  @graphql-eslint/no-deprecated

***/src/User1.fragment.gql
  4:4  warning  This field is marked as deprecated in your GraphQL schema (reason: Use `firstName` instead.)  @graphql-eslint/no-deprecated

***/src/User2.fragment.gql
  4:4  warning  This field is marked as deprecated in your GraphQL schema (reason: Use `firstName` instead.)  @graphql-eslint/no-deprecated

✖ 3 problems (0 errors, 3 warnings)
```

**Environment:**

- OS: `macOS Catalina`
- `@graphql-eslint/eslint-plugin@:` `0.9.1`
- NodeJS: `v14.13.1`

**Additional context**

**Comment by B2o5T** [comment]
You need to use `processor: '@graphql-eslint/graphql'` only on javascript/typescript files as it's mention in readme, your config is wrong, you must write overrides object for them with graphql-eslint processor

**Comment by lukaskl** [comment]
Yes, I understand that `processor: '@graphql-eslint/graphql'` is used to process javascript/typescript files. However, it is possible that users will have GraphQL documents in both javascript/typescript files and `.graphql` files, e.g. while they are in transition.

Having in mind, that:
- I've took configuration from [the examples](https://github.com/dotansimha/graphql-eslint/blob/%40graphql-eslint/eslint-plugin%400.9.1/examples/graphql-config-code-file/.eslintrc.json)
- It seems that it is really close to make it working in combination, i.e. support both javascript/typescript files and `.graphql` files parsing together - there are just comments which cause failures.

I believe it was still worthy to create this issue. At least as a lower priority bug / polishing issue.

**Comment by dotansimha** [comment]
I think @B2o5T is right here. @lukaskl can you please try that and let us know?

**Comment by lukaskl** [comment]
I can confirm that, moving `processor: '@graphql-eslint/graphql',` inside of the `overrides` works well 👍 
Thank you. 

And if there is no wish to do anything here more (e.g. documentation or examples update), then we can simply close this ticket.
