### ISSUE TITLE
graphql blocks skipped when passing `--ext` argument

### ISSUE THREAD

**Issue by amneacsu** [dotansimha/graphql-eslint#443]
**Describe the bug**

GraphQL blocks are ignored when running `eslint` from the command line, and an `--ext` argument is passed.

**To Reproduce**

Just the most basic setup, using eslint's `--ext` CLI argument. Unfortunately I don't think the issue can be reproduced in codesandbox because it needs the CLI.

https://codesandbox.io/s/vigilant-rgb-p6uv4

**Expected behavior**

Expected graphql lint rules to work in the CLI.

**Environment:**

- OS: MacOS 11.3.1 (20E241)
- `@graphql-eslint/...`: 1.0.1
- NodeJS: 12.10
- yarn 1.22.5

**Additional context**

Rules work in Atom and VSCode, I guess because they ignore npm scripts and lint everything.

<details>
<summary>Some sample eslint debug output</summary>

```
eslint:cli-engine Lint /.../src/test.js +0ms
eslint:linter Linting code for /.../src/test.js (pass 1) +0ms
eslint:linter Verify +0ms
eslint:linter With ConfigArray: /.../src/test.js +0ms
eslint:linter Apply the processor: '@graphql-eslint/graphql' +0ms
eslint:linter A code block was found: 'document.graphql' +14ms
eslint:linter This code block was skipped. +1ms
```

</details>

**Comment by B2o5T** [comment]
This is expected behavior as all graphql code inside `js/ts` files will be parsed and for that files will be created virtual filenames like `/Users/dimitri/Desktop/eslint-issue/src/index.js/0_document.graphql` for your first extracted operation, so passing `--ext .js` flag to eslint will ignoring all linting for your real and virtual graphql files

**Comment by B2o5T** [comment]
You don't have to provide `max-len`, `no-multiple-empty-lines` for all files, only for `js`
