### ISSUE TITLE
GraphQLRuleTester not available

### ISSUE THREAD

**Issue by apexskier** [dotansimha/graphql-eslint#495]
**Describe the bug**

The GraphQLRuleTester class described in the custom rules docs (https://github.com/dotansimha/graphql-eslint/blob/master/docs/custom-rules.md#testing-your-rules) isn't available.

**To Reproduce**

Install `@graphql-eslint/eslint-plugin` locally, and run the following in a node repl. The object is undefined

```
> const { GraphQLRuleTester } = require("@graphql-eslint/eslint-plugin")
undefined
```

**Expected behavior**

I'd expect this to be exported so I can write a test as documented.

**Environment:**

- OS: macOS
- `@graphql-eslint/...`: `"@graphql-eslint/eslint-plugin": "^1.0.1",`
- NodeJS: 12.22.1

**Comment by dotansimha** [comment]
oops, definitely a missing export! 

Fixed in `@graphql-eslint/eslint-plugin@1.0.2`.
