### ISSUE TITLE
ESLint directives no longer working on nonvirtual files

### ISSUE THREAD

**Issue by B2o5T** [dotansimha/graphql-eslint#504]
**Describe the bug**
ESLint directives no longer working on nonvirtual files

**To Reproduce**
Since we have fixed a bug to support `#import` comments, now nonvirtual files we parse with `GraphQLFileLoader` instead of `parseGraphQLSDL`, but after parsing `rawSDL` with `GraphQLFileLoader` all comments are trimmed.

**Environment:**

- OS: macOS
- `@graphql-eslint/...`: 1.1.0
- NodeJS: 14.16.0

**Comment by ardatan** [comment]
@B2o5T Can we create a failing test on graphql-tools?

**Comment by B2o5T** [comment]
@ardatan Done 🙂 Let me know what do you think

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@1.1.1`
