### ISSUE TITLE
Nested imported fragments can give false positives on unique-fragment-name

### ISSUE THREAD

**Issue by lennartbuit** [dotansimha/graphql-eslint#507]
**Describe the bug**

When a query imports a fragment (using `#import`) that itself also imports another fragment, all documents are reported as to having a duplicate fragment names.

**To Reproduce**

Check out this gist: https://gist.github.com/lennartbuit/3d0141b62432c133ca553de15792ad17

In this setup, I have a query importing fragment A that itself imports fragment B.

Running `yarn eslint *.graphql` will flag all files as having violations of the unique-fragment-name rule:

<img width="590" alt="Screenshot 2021-06-29 at 21 35 30" src="https://user-images.githubusercontent.com/37534243/123857062-2488e980-d922-11eb-90e6-e57a0e4b0d68.png">

**Expected behavior**

No reported errors. Fragments are only defined once, after all.

**Environment:**

- OS: Mac OS
- `@graphql-eslint/...`: 1.1.0
- NodeJS: v14.16.1

**Additional context**

**Comment by lennartbuit** [comment]
[I can spin this out in a seperate issue if you'd like] The `@graphql-eslint/no-unused-fragments` also doesn't handle this situation of nested imports correctly:

<img width="622" alt="Screenshot 2021-06-29 at 23 56 06" src="https://user-images.githubusercontent.com/37534243/123874535-a1bf5900-d938-11eb-80c5-6477fc6e9e22.png">

I would have expected fragments to be considered used if they were imported by imports of intermediate fragments.

**Comment by B2o5T** [comment]
Thank you @lennartbuit your description is very helpful, we'll fix this very soon!

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@1.1.1`

**Comment by lennartbuit** [comment]
Thank you both! Checked with my original codebase and confirmed fixed the issue there as well!
