### ISSUE TITLE
Evaluating recommended ruleset

### ISSUE THREAD

**Issue by mhatvan** [dotansimha/graphql-eslint#552]
**Is your feature request related to a problem? Please describe.**

At the current project I am working on, we are in the process of evaluating a recommended ruleset for our usage of `graphql-eslint`, since there is none yet unfortunately. The project is quite big with 50+ packages in a monorepo structure, so this plugin will have a great impact (thanks for making it!)

Basically, around 5-7 people in our team will vote on keeping or removing rules for our ruleset and then we will agree on the final ruleset. I can post the resulting ruleset here, then it could be further discussed and potentially implemented in `graphql-eslint` as recommended to make devs work easier!

**Comment by dotansimha** [comment]
Hi @mhatvan ! We'll be really happy to hear your thoughts and ideas! Thank you for this valuable feedback, and thank you for taking the time to open this issue! :) 

Please, feel free to share with us your set of recommended rules and configuration, and feel free to share any feedback regarding the library itself.

**Comment by mhatvan** [comment]
Sure thing, the least I can do for using such a great library!

It will still take a couple of days until all relevant devs will decide on the ruleset, then I will let you know right away.

**Comment by mhatvan** [comment]
It took a bit longer since we only have bi-weekly crew days, but here is the first rough draft:
https://gist.github.com/mhatvan/160b533836bcf9fa5ce01c9f47d101da

It's in a gist because it will still need some iterations until its finished.

This is how to read the ruleset:
- rules that are enabled and set to 1 are rules that had > 50% approval rating
- rules that are commented out and set to 1 are rules that had < 50% approval rating, might still be discussed internally
- rules that are set to 0 are rules that everyone voted to remove
- rules that are commented out with `TODO:` are wanted, but we are having issues with it currently

**Comment by dotansimha** [comment]
Thanks @mhatvan !! 
Recently @B2o5T added some setup for the recommended rules-set, I think it's based on this list, right?

**Comment by B2o5T** [comment]
@dotansimha at the moment I added to recommended config only all rules from `graphql-js` and the rules that already had `recommended: true`. Also, I found that some of our rules need to have an additional configuration like [naming-convention](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md#correct), so we need to think about

**Comment by dotansimha** [comment]
Closing, the new rules set is available in `@graphql-eslint/eslint-plugin@3.0.0`
