### ISSUE TITLE
New rule: avoid duplicate definitions

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [dotansimha/graphql-eslint#74]

**Comment by ilyavolodin** [comment]
Unfortunately, this would require full schema. ESLint operates on one file at a time, so there isn't an easy way to collect full schema if you have definitions spread amongst multiple files.

**Comment by FluorescentHallucinogen** [comment]
> ESLint operates on one file at a time

This is a significant limitation. This makes most of the useful rules infeasible.

> this would require full schema
> there isn't an easy way to collect full schema

`graphql-eslint` uses [graphql-config](https://graphql-config.com) under the hood. What about using it to get the full GraphQL schema?

**Comment by FluorescentHallucinogen** [comment]
> ESLint operates on one file at a time

Is there a plan to change this? If so, is there an issue about this in the ESLint repo?

**Comment by ilyavolodin** [comment]
> This is a significant limitation. This makes most of the useful rules infeasible.

I wouldn't say "most" but yes, that does provide a limitation on some rules.

> `graphql-eslint` uses graphql-config under the hood. What about using it to get the full GraphQL schema?

It's possible, but it wouldn't be very straight forward. ESLint works on each file individually it also reports all issues individually per file as well, if you were to start linting the whole schema all the time, you will end up with a large number of duplicate errors, and in most cases those errors will happen outside of the file that you are currently linting. I'm sure there's some work-around that we can come up with, but it will not be trivial. One way I would like to explore at some point is to try to register "scopes" with ESLint for the entire schema. ESLint has full support for scopes and we could populate scopes from the schema constructed by `graphql-config`. This would, at the very least allow us to check if there are missing types.

> Is there a plan to change this? If so, is there an issue about this in the ESLint repo?

There were a bunch of conversations about it amongst ESLint's TSC, but it never was made a priority. ESLint has been a de-facto linter for JavaScript/Typescript for over 6 years now without this feature, there isn't any other linter that even comes close to the functionality of ESLint, so as such, this was deemed a low priority enhancement.

**Comment by dotansimha** [comment]
We do support this now with the siblings operation loaded sync using `@graphql-tools` loaders. (https://github.com/dotansimha/graphql-eslint/issues/7)

**Comment by dotansimha** [comment]
Available since `0.6.0`
