### ISSUE TITLE
limit input-name to Mutation fields only

### ISSUE THREAD

**Issue by BigsonLvrocha** [dotansimha/graphql-eslint#75]
There is conflict with the rule input-name where it will return error on connection fields, node id input etc.

**Comment by dotansimha** [comment]
Hi @BigsonLvrocha ! Can you please share an example? 
fyi @ilyavolodin

**Comment by BigsonLvrocha** [comment]
This is the base query for a schema following relay's specification
![Screenshot from 2020-10-05 16-28-01](https://user-images.githubusercontent.com/14062008/95123393-443f0880-0728-11eb-9cd6-1c58dd7dfbfa.png)

**Comment by ilyavolodin** [comment]
Oh, good find. Yes, that seems like a bug

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@0.4.3`, thank you @henryqdineen !
