### ISSUE TITLE
Update graphql dependency to support graphql 16.0

### ISSUE THREAD

**Issue by davidbernegger** [dotansimha/graphql-eslint#761]
The current version of graphql dependencies only goes up until Graphql 15 - it would be nice if the newest version would be supported :)

![image](https://user-images.githubusercontent.com/16232537/140809143-a513ba85-4fe7-4b58-a50a-813ef42da20f.png)

**Comment by ardatan** [comment]
Actually it supports v16 but it seems peerDependencies haven't been updated yet

**Comment by davidbernegger** [comment]
Then i'll close this! Thanks for the info!
