### ISSUE TITLE
New rule: require deprecated date

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [dotansimha/graphql-eslint#77]
And as idea, suggest to remove deprecated things after deprecated date.

**Comment by FluorescentHallucinogen** [comment]
https://speakerdeck.com/xuorig/graphql-schema-design-at-scale?slide=88

**Comment by FluorescentHallucinogen** [comment]
See also https://github.com/kamilkisiela/graphql-inspector/issues/215.

**Comment by dotansimha** [comment]
Available in `@graphql-eslint/eslint-plugin@2.2.0`
