### ISSUE TITLE
eslint plugin: parserOptions.operations doesn't work if skipGraphQLConfig is false

### ISSUE THREAD

**Issue by jared-dykstra** [dotansimha/graphql-eslint#770]
**Describe the bug**

If using *both* the eslint config and graphql config files, _and_ if a rule like `'@graphql-eslint/unique-operation-name': 'error'` is configured, the following error results:
```
Error: Rule 'unique-operation-name' requires 'parserOptions.operations' to be set and loaded. See http://bit.ly/graphql-eslint-operations for more info
```

Workaround: disable the graphQL config by adding `skipGraphQLConfig: true` and `schema` to the `parserOptions` section.
```jsonc
      parserOptions: {
        // List all Queries & Mutations
        operations: ['./src/**/*.{gql,graphql}'],
        // Note - The default (using GraphQLConfig) seems to overwrite parserOptions.options.  Workaround by disabling it
        skipGraphQLConfig: true,
        schema: '<path to your introspection schema file>.json',
      },
```

**To Reproduce**
Some of the eslint rules require `parserOptions.operations` to bet set to an array of files containing all queries and mutations.  Unfortunately, if the project is using both `.eslintrc.js` and `graphql.config.js` files, the graphql config file appears to cause `parserOptions.operations` to be undefined.

**Expected behavior**
The rules should function normally, without error

**Environment:**

- OS: macOS
- `@graphql-eslint/plugin`:
- NodeJS: v12.22.4

**Additional context**
Running eslint on just the gql files from the command line via: `./node_modules/.bin/eslint ./src --ext .gql`.  The behavior within VSCode will show the same error message as a toast style popup.

**Comment by B2o5T** [comment]
Hi @jared-dykstra, if you use `graphql-config` you must specify your operations not via `parserOptions.operations` but via `documents` property in your `graphql-config` file, more info <https://graphql-config.com/documents>

@dotansimha maybe we will rename `parserOptions.operations` to `parserOptions.documents` to make consistency with `graphql-config` in next major version ?

**Comment by jared-dykstra** [comment]
That is excellent.  I didn't know that all I needed to do is use `documents` in my `graphql.config.js`.  It works perfectly.

**Comment by joshribakoff-sm** [comment]
This should really be documented more explicitly, or result in a better error message! I have been spending hours debugging and stepping through code, and finally I found this issue and tried adding `documents` which fixed the issue!

Thanks!
