### ISSUE TITLE
GitHub/CI bot

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [dotansimha/graphql-eslint#78]
What about GitHub/CI action/app like [GraphQL Inspector](https://graphql-inspector.com)?

As an idea, it could be called GraphQL Doctor.

GraphQL Inspector is about detecting changes and preventing breaking changes in GraphQL schema.

GraphQL Doctor is about validating and force best design practices in GraphQL schema.

**Comment by ilyavolodin** [comment]
There's already a github action created for ESLint by Github team. This plugin should be able to just piggy-back on that.

**Comment by dotansimha** [comment]
Hi! 
Actually, GraphQL Inspector is also a library that was created by [us](http://the-guild.dev/), @kamilkisiela . 
I see GraphQL-Inspector as a way to have better collaboration while developing a GraphQL architecture, and it solves different problems. GraphQL-ESLint should focus mainly on the local setup, and should provide details based on your local files. 

@ilyavolodin is 100% correct, there is a ESLint [action](https://github.com/marketplace/actions/run-eslint) but you can just use `run` and run `eslint` as-is...
