### ISSUE TITLE
no-hashtag-description rule applies to operations

### ISSUE THREAD

**Issue by dobesv** [dotansimha/graphql-eslint#817]
**Describe the bug**

It appears that the `@graphql-eslint/no-hashtag-description` rule will apply to operations, even though you cannot add descriptions to operations using a string.

**To Reproduce**

```
# This is a comment that will trigger no-hashtag-description
query Q {
  thisIsAQuery {
    id
  }
}
```

**Expected behavior**

`no-hashtag-description` should only trigger for fields & types.

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@3.1.0` 🎉 thanks @B2o5T
