### ISSUE TITLE
README - outdated paragraph about Prettier

### ISSUE THREAD

**Issue by rtrembecky** [dotansimha/graphql-eslint#855]
**Context**
Prettier is supported out-of-the-box from https://github.com/prettier/eslint-plugin-prettier/pull/413.

**Solution**
Remove the related paragraph from README.

**Alternatives**
Add info that the Prettier-related changes are needed just for the older plugin versions.

Sorry for not creating a PR right away.

**Comment by B2o5T** [comment]
Thank you @rtrembecky, it was finally merged 😅, I'll update README and examples with prettier

**Comment by B2o5T** [comment]
Hi @rtrembecky, https://github.com/prettier/eslint-plugin-prettier/pull/415 this PR must be merged also for removing unnecessary overrides

**Comment by rtrembecky** [comment]
Does it? I don't know, I don't have any issues using `eslint-plugin-prettier` now without additional configuration, and the README is talking just about that plugin as well. So maybe it's a separate issue?
ref. README part: https://github.com/dotansimha/graphql-eslint#prettier-rule

**Comment by B2o5T** [comment]
this is because your schema is located in `graphql` files, try to remove `files: ['*.js/*.graphql']` override block in [examples/prettier](https://github.com/dotansimha/graphql-eslint/blob/master/examples/prettier/.eslintrc.js#L24L29) and you'll see different result - 31 errors vs 23 errors

**Comment by rtrembecky** [comment]
Right, that would be it, thanks for the explanation. Closing this, I guess https://github.com/prettier/eslint-plugin-prettier/pull/415 is enough to track this and it will be noticed when it gets merged 🙂
