### ISSUE TITLE
Parsing error: File foo.graphql doesn't match any projects

### ISSUE THREAD

**Issue by mwjaco** [dotansimha/graphql-eslint#890]
**Describe the bug**

This may be a duplicate of https://github.com/dotansimha/graphql-eslint/issues/479. I have followed the README as closely as I can, adapting it a little, but I encounter the error "Parsing error: File foo/bar/baz.graphql doesn't match any projects" whenever I open a file with a `.graphql` extension.

**To Reproduce**
My ESLint configuration:

```
module.exports = {
  env: {node: true},
  extends: ['airbnb-typescript', 'plugin:prettier/recommended', 'plugin:jsdoc/recommended'],
  parserOptions: {project: './tsconfig.json'},
  rules: {
    'class-methods-use-this': 0,
    'import/no-unresolved': 0,
    'import/order': [
      1,
      {
        groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index', 'object'],
        'newlines-between': 'always-and-inside-groups'
      }
    ],
    'no-restricted-syntax': 0,
    'no-use-before-define': [2, 'nofunc']
  },
  overrides: [
    {
      files: './src/**/*.graphql',
      parser: '@graphql-eslint/eslint-plugin',
      plugins: ['@graphql-eslint'],
      rules: {
        '@graphql-eslint/known-type-names': 'error'
      },
      parserOptions: {
        operations: './src/**/*.graphql',
        schema: './src/foo/bar/schema.graphql'
      }
    }
  ]
};
```

Per the README I also tried passing `files: ['*.graphql']` to my `overrides` but that didn't resolve the error.

**Expected behavior**
`.graphql` files should be linted without errors

**Environment:**
- OS: MacOS Mojave 10.14.6
- `@graphql-eslint/...`: 3.6.0
- NodeJS: 12.18.0

**Comment by B2o5T** [comment]
Hi, to help you I need a reproduction repo

**Comment by mwjaco** [comment]
I believe I've resolved my issue!

In my case, extending `airbnb-typescript` seemed to require all other parsers, even in my `overrides`, to expect `project: './tsconfig.json'` in their `parserOptions`. I refactored my TypeScript plugins and rules into their own overrides per [this recommendation](https://stackoverflow.com/a/64488474/1181150) and now `graphql-eslint` is correctly linting my `.graphql` files. Thanks for your patience.

**Comment by B2o5T** [comment]
Nice!

Yeah, it's important that you don't have any rules configured at the top-level config, and to move all configurations into the `overrides` section. Since JavaScript rules can't run on GraphQL files and vice versa, if you have rules configured at the top level, they will try to also execute for all `overrides`, as ESLint's configs cascade.

I already showed it in [examples](https://github.com/dotansimha/graphql-eslint/blob/master/examples/basic/.eslintrc.js#L4-L10). I think we need to improve docs for that.
