### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by ahmafi** [dotansimha/graphql-eslint#894]
[Here](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/strict-id-in-types.md#correct) in the docs, `acceptedIdTypes` is only set to `ID`, but in the next lines an ID with type `String` is accepted as a correct syntax.

**Comment by B2o5T** [comment]
Nope, there is nothing wrong, your link point on the **example** of a configuration for this rule, and below described all available options and expected values for this rule

**Comment by ahmafi** [comment]
I don't think that `exceptions` allow the use of `String`.

![String](https://user-images.githubusercontent.com/12560109/148636119-2ff4d1d7-f1fa-483c-b00a-8709df81918a.png)

I get the error with the line in the docs:
![ID](https://user-images.githubusercontent.com/12560109/148636183-622bcdd0-fa31-463b-9df4-19961c9cbff3.png)
