### ISSUE TITLE
Allow `match-document-filename` to accept `ignorePattern`

### ISSUE THREAD

**Issue by nahtnam** [dotansimha/graphql-eslint#919]
**Is your feature request related to a problem? Please describe.**

Currently, `match-document-filename` does not let you provide `ignorePattern`. Problem is if I provide `ignorePattern` to `naming-convention` then the file names will not match some of the time.

**Describe the solution you'd like**

See above

**Describe alternatives you've considered**

Either allowing `ignorePattern` to `match-document-filename` OR allowing a new style called "original" where it just takes the name of the operation without any modification would solve this

**Additional context**

N/A

**Comment by B2o5T** [comment]
I am okay with adding a new style option for fixing your case.
But what will be the best comprehensive name for that case? 😅

My propositions for new style name:

- `original`
- `same`
- `sameAsDocument`
- `documentStyle`

**Comment by nahtnam** [comment]
Sorry, got lost in my email! I personally think `documentStyle` is a bit confusing when you have no context. I prefer `sameAsDocument` or `matchDocumentName`. What do you think?

**Comment by B2o5T** [comment]
@nahtnam I think `matchDocumentStyle` is most clear, will rename 👍

**Comment by dotansimha** [comment]
Fixed in `@graphql-eslint/eslint-plugin@3.8.0` 🎉
