### ISSUE TITLE
Allow rule to be reliably overridden using `eslint-disable-line`

### ISSUE THREAD

**Issue by dchambers** [dotansimha/graphql-eslint#942]
**Describe the bug**

The `no-typename-prefix` rule (and seemingly others -- see below) requires `eslint-disable-next-line` to be used if the field in question has a non-block description, and can only have a targeted override using `-disable-start` and `-disable-end` if a block description is used.

**To Reproduce**

Verify that this works:

```gql
type Type {
  typeName: String! # eslint-disable-line @graphql-eslint/no-typename-prefix
}
```

and this:

```gql
type Type {
  "Some description" # eslint-disable-next-line @graphql-eslint/no-typename-prefix
  typeName: String!
}
```

but not this:

```gql
type Type {
  "Some description"
  typeName: String! # eslint-disable-line @graphql-eslint/no-typename-prefix
}
```

**Expected behavior**

It should be possible to reliably disable all rules using `-disable-line` overrides only.

**Additional context**

The line number can be wrong here because the given `loc` node is for the parent `FieldDescription` instead of the child `NameNode`, and this problem seems fairly widespread, though not in all rules.

One possible way of reliably enforcing this for all rules would be to use the type system to ensure that only leaf nodes could be passed to `getLocation`, though this would require a large list of types to be defined. Alternatively, a run-time `isLeafNode` check could be used to achieve the same thing. Both approaches would require that the node containing the `loc` property be passed to `getLocation` instead of the location node itself.

Since the governance mechanism we want to build using `graphql-eslint` requires a reliable way to do single-line overrides, I created a spike to see how widespread this issue was, and whether a reliable solution could be found. I'm not sure it's the best approach, but all tests do pass, and it did find a number of rules that weren't using leaf nodes.

Code here:

- https://github.com/dotansimha/graphql-eslint/compare/master...dchambers:spike-disallow-non-leaf-node-locations?expand=1

**Comment by B2o5T** [comment]
Hi @dchambers, thank you for your report, could you say if now it works as expected?
```gql
type Type {
  "Some description"
  typeName: String! # eslint-disable-line no-typename-prefix
}
```
I tested this code on the latest version of `graphql-eslint@3.8.0` and seems like this problem was fixed (recently I made some refactoring for extracting tokens and comments).

**Comment by dchambers** [comment]
> I tested this code on the latest version of `graphql-eslint@3.8.0` and seems like this problem was fixed (recently I made some refactoring for extracting tokens and comments).

Wow, this project is moving seriously fast! 🚅  Thanks so much 🙏
